bags:
  bag1:
    crop: tomato
    camera: rooftop_cam_1
    roi:
      x: 100
      y: 150
      width: 500
      height: 350

  bag2:
    crop: spinach
    camera: rooftop_cam_1
    roi:
      x: 650
      y: 150
      width: 500
      height: 350
